Discourage local-FS-only methods
magento/magento-coding-standard pull request #198
Opened 2020-11-12 16:27 UTC by shiftedreality

This PR adds` getimagesize()`  to discouraged functions as it does not work with remote storage implementations.

Task: https://jira.corp.magento.com/browse/MC-38508

2020-11-19 15:52 UTC, sidolov requested changes

2020-11-19 15:52 UTC, sidolov commented on Magento2/Sniffs/Functions/DiscouragedFunctionSniff.php
> +        'getimagesize' => 'getimagesizefromstring',
Should it be `^getimagesize$`?

2020-11-19 15:56 UTC, shiftedreality commented on Magento2/Sniffs/Functions/DiscouragedFunctionSniff.php
> +        'getimagesize' => 'getimagesizefromstring',
Fixed

2020-11-19 16:00 UTC, sidolov commented
@magento import pr to magento-commerce/magento-coding-standard

2020-11-19 16:01 UTC, magento-engcom-team commented
@sidolov the pull request successfully imported.

2020-11-20 07:03 UTC, ihor-sviziev commented
@shiftedreality could you put some docs why it was discouraged? I think the message that it's just discourages isn't clear ata all.

2020-11-30 21:01 UTC, shiftedreality commented
@ihor-sviziev do you have any example of how it should be documented? Is there any section in DevDocs?

2020-11-30 21:46 UTC, ihor-sviziev commented
@shiftedreality sample: https://github.com/magento/magento-coding-standard/blob/develop/Magento2/Sniffs/Performance/ForeachArrayMergeSniff.md

2020-11-30 21:58 UTC, shiftedreality commented
@ihor-sviziev thanks, added

2020-11-30 22:06 UTC, ihor-sviziev submitted a review, later dismissed

2020-12-03 04:18 UTC, ihor-sviziev approved these changes

2020-12-03 12:53 UTC, sivaschenko commented
@magento import pr to magento-commerce/magento-coding-standard

2020-12-03 12:54 UTC, magento-engcom-team commented
@sivaschenko the pull request successfully imported.

2020-12-03 13:05 UTC, merged