AC-660: Create phpcs static check for DiConfigTest
magento/magento-coding-standard pull request #233
Opened 2021-08-25 11:06 UTC by loginesta

This sniffer looks for occurrences of obsolete nodes: `param`, `instance`, `array`, `item[@key]` and `value`.
Returns a warning for each occurrence found.

2021-08-25 11:41 UTC, sivaschenko requested changes
Thanks for the pull request @loginesta ! Can you please verify the test functionality running it against the Magento code with changed di.xml files?

2021-08-25 11:41 UTC, sivaschenko commented on Magento2/ruleset.xml
> +        <include-pattern>*\/DiConfigUnitTest.xml$</include-pattern>
Is this test for di.xml files only?
```suggestion
        <include-pattern>*\/di.xml$</include-pattern>
```

2021-08-25 12:27 UTC, svera commented on composer.json
> +        "ext-dom": "*"
You need to update also `composer.lock`

2021-08-25 12:54 UTC, loginesta commented on composer.json
> +        "ext-dom": "*"
forgot to push it 😉  thanks

2021-08-30 09:38 UTC, sivaschenko approved these changes

2021-08-30 09:38 UTC, sivaschenko commented
@magento import pr to magento-commerce/magento-coding-standard

2021-08-30 09:39 UTC, magento-engcom-team commented
@sivaschenko the pull request successfully imported.

2021-08-30 09:39 UTC, svera approved these changes

2021-08-30 10:31 UTC, merged