AC-667: Create phpcs static check for EmailTemplateTest
magento/magento-coding-standard pull request #261
Opened 2021-09-07 09:26 UTC by jcuerdo

2021-09-07 09:39 UTC, loginesta commented on Magento2/Tests/Legacy/EmailTemplateUnitTest.2.html
> +<p class="greeting">{{trans "Translateme"}}</p>
no new line at the end of file

2021-09-07 09:39 UTC, loginesta submitted a review, later dismissed
LGTM

2021-09-07 10:22 UTC, jcuerdo commented on Magento2/Tests/Legacy/EmailTemplateUnitTest.2.html
> +<p class="greeting">{{trans "Translateme"}}</p>
Done

2021-09-07 11:34 UTC, sivaschenko requested changes
Great first contribution, @jcuerdo ! Please see my comments

2021-09-07 11:34 UTC, sivaschenko commented on Magento2/ruleset.xml
I'd remove this empty line for consistency.

2021-09-07 11:34 UTC, sivaschenko commented on Magento2/ruleset.xml
> +        <type>warning</type>
I think this should be an error as using of obsolete directives will actually harm the functionality of email templates

2021-09-07 16:09 UTC, svera submitted a review, later dismissed

2021-09-07 16:10 UTC, sivaschenko commented on Magento2/ruleset.xml
> +        <severity>8</severity>
Please move it to the section with errors in the beginning of this file
```suggestion
        <severity>10</severity>
```

2021-09-08 09:41 UTC, sivaschenko approved these changes

2021-09-08 09:45 UTC, jcuerdo commented
@magento import pr to magento-commerce/magento-coding-standard

2021-09-08 09:46 UTC, magento-engcom-team commented
@jcuerdo the pull request successfully imported.

2021-09-08 10:21 UTC, merged