Fixed wrongly returning error for valid descriptions
magento/magento-coding-standard pull request #270
Opened 2021-09-13 15:10 UTC by svera

#140 was wrongly returning error for valid short descriptions. We added several unit tests checking for this issue, as well as not allowing to repeat property class name in short description and rephrasing the error return when a short description is placed after a @var annotation.

2021-09-13 16:41 UTC, sivaschenko requested changes
Thank you for the fix @svera ! Please see my comments

2021-09-13 16:41 UTC, sivaschenko commented on Magento2/Sniffs/Commenting/ClassPropertyPHPDocFormattingSniff.php
> +        if (stripos($tokens[$isShortDescriptionPreviousVar]['content'], $tokens[$string]['content']) !== false) {
Please check that $isShortDescriptionPreviousVar is not false before using it as an array key

2021-09-13 16:41 UTC, sivaschenko commented on Magento2/Sniffs/Commenting/ClassPropertyPHPDocFormattingSniff.php
> +        }
I don't think finding a part of property name in the description should fail the test, I'd rather check if the short description matches the split variable name.
```suggestion
            if (stripos($tokens[$isShortDescriptionPreviousVar]['content'], implode(' ', $varTagParts)) === false) {
                return;
            }
```

2021-09-14 08:51 UTC, sivaschenko approved these changes

2021-09-14 08:59 UTC, svera commented
@magento import pr to magento-commerce/magento-coding-standard

2021-09-14 09:10 UTC, merged