Ac 669 install upgrade test
magento/magento-coding-standard pull request #281
Opened 2021-09-23 07:48 UTC by svera

This sniff checks that no obsolete upgrade files are used, pointing to modern alternatives in that case.

2021-09-23 14:50 UTC, loginesta approved these changes

2021-09-23 15:10 UTC, jcuerdo requested changes

2021-09-27 08:53 UTC, svera commented
@magento import pr to magento-commerce/magento-coding-standard

2021-09-27 08:53 UTC, m2-github-services commented
@svera the Pull Request is successfully imported.

2021-09-27 09:02 UTC, merged