AC-677: Create phpcs static test for ObsoleteMenuTest
magento/magento-coding-standard pull request #288
Opened 2021-09-28 10:42 UTC by loginesta

https://jira.corp.magento.com/browse/AC-677 Create phpcs static test for ObsoleteMenuTest

2021-09-29 13:54 UTC, jcuerdo submitted a review, later dismissed

2021-09-29 14:50 UTC, eliseacornejo requested changes

2021-09-29 14:50 UTC, eliseacornejo commented on Magento2/ruleset.xml
> +        <include-pattern>*\/widget.xml$</include-pattern>
This need to be done in widget.xml files? Shouldn't this need to be done in config.xml files?

2021-09-29 15:29 UTC, eliseacornejo submitted a review, later dismissed

2021-09-30 08:26 UTC, eliseacornejo approved these changes

2021-09-30 08:35 UTC, jcuerdo approved these changes

2021-09-30 08:40 UTC, loginesta commented
@magento import pr to magento-commerce/magento-coding-standard

2021-09-30 08:40 UTC, m2-github-services commented
@loginesta the Pull Request is successfully imported.

2021-09-30 08:52 UTC, merged