Added Constant visibility in the ruleset
magento/magento-coding-standard pull request #330
Opened 2021-11-09 14:00 UTC by rmsundar1

### Description (*)
Added Constant visibility check in the ruleset

### Fixed Issues (if relevant)
1. Fixes magento/magento-coding-standard#174

2021-11-09 14:24 UTC, ihor-sviziev submitted a review, later dismissed

2021-11-10 13:15 UTC, sivaschenko requested changes
Thanks for the improvement @rmsundar1 . Please take a look at my comment

2021-11-15 14:26 UTC, sivaschenko approved these changes

2021-11-15 14:26 UTC, sivaschenko commented
@magento import pr to magento-commerce/magento-coding-standard

2021-11-15 14:27 UTC, m2-github-services commented
@sivaschenko the Pull Request is successfully imported.

2021-11-15 14:37 UTC, merged