Add semicolon as statement separator in the special annotation check of the `Magento2.Security.XssTemplate` sniff
magento/magento-coding-standard pull request #378
Opened 2022-03-04 19:37 UTC by aadmathijssen

This PR improves special annotation detection of the `Magento2.Security.XssTemplate` sniff by adding `T_SEMICOLON` as a statement separator. This resolves the issue that violations in a statement might be ignored by a special annotation in a previous/subsequent statement.

For example, consider the following file:

```phtml
<?php
    /* @noEscape */ echo $foo;
    echo $bar;
?>
<?=
    $baz;
    /* @noEscape */ echo $qux;
?>
```

This does not reported any violations of the `Magento2.Security.XssTemplate` sniff.

However, the statements involving `$bar` and `$baz` should report a `FoundUnescaped` violation.

This PR makes sure this is done, such that the following is reported:

```
FILE: /path/to/file.phtml
-----------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
-----------------------------------------------------------------------------------------
 3 | WARNING | Unescaped output detected.
   |         | (Magento2.Security.XssTemplate.FoundUnescaped)
 6 | WARNING | Unescaped output detected.
   |         | (Magento2.Security.XssTemplate.FoundUnescaped)
-----------------------------------------------------------------------------------------
```

2023-01-26 12:30 UTC, fredden reviewed
The code changes look good to me. Please can you add a test case to cover this change.

2023-06-12 10:14 UTC, ihor-sviziev requested changes
Please add test coverage for your changes

2023-09-20 16:47 UTC, sidolov commented
@magento import PR to magento-commerce/magento-coding-standard repository

2023-09-20 16:48 UTC, m2-github-services commented
@sidolov the Pull Request is successfully imported.

2023-09-20 17:11 UTC, merged